// Initial Seed Data for ELIMU PRO
import { 
  School, ClassStream, Department, Subject, SubjectCombination, 
  Teacher, Student, Examination, MarkEntry, ExamSubmissionSummary,
  User, Announcement, MessageGroup, GroupMessage, SMSLog, AuditLog, StudentAttendanceRecord
} from '../types';

export const INITIAL_SCHOOL: School = {
  id: 'school_tura_01',
  name: 'TURA SECONDARY SCHOOL',
  registrationNumber: 'S.3892',
  motto: 'Elimu ni Msingi wa Maisha na Maendeleo',
  region: 'Tabora Region',
  district: 'Uyui District',
  box: 'P.O. Box 244, Tura - Uyui, Tabora',
  phone: '+255 784 122 334',
  email: 'info@turasecondary.sc.tz',
  website: 'https://turasecondary.sc.tz',
  currentAcademicYear: '2026',
  currentTerm: 'Term 1',
  principalName: 'Mwl. Baraka E. Mushi',
  academicMasterName: 'Mwl. Grace K. Mwita',
};

export const INITIAL_DEPARTMENTS: Department[] = [
  { id: 'dept_sci', name: 'Science Department', code: 'SCI', headOfDepartmentId: 'tch_04', headOfDepartmentName: 'Mwl. Daudi J. Tarimo', description: 'Physics, Chemistry, and Biology laboratories and instructions' },
  { id: 'dept_math', name: 'Mathematics Department', code: 'MATH', headOfDepartmentId: 'tch_05', headOfDepartmentName: 'Mwl. Asha M. Salum', description: 'Basic Mathematics, Advanced Mathematics, and BAM' },
  { id: 'dept_lang', name: 'Languages Department', code: 'LANG', headOfDepartmentId: 'tch_07', headOfDepartmentName: 'Mwl. Tumaini L. Swai', description: 'Kiswahili, English Language, and French' },
  { id: 'dept_hum', name: 'Humanities & Social Sciences', code: 'HUM', headOfDepartmentId: 'tch_06', headOfDepartmentName: 'Mwl. Emmanuel P. Shirima', description: 'Geography, History, and Civics' },
  { id: 'dept_comm', name: 'Commercial Department', code: 'COMM', description: 'Economics, Commerce, and Bookkeeping' },
];

export const INITIAL_SUBJECTS: Subject[] = [
  // O-Level
  { id: 'sub_math_o', code: 'MATH', name: 'Basic Mathematics', level: 'O_LEVEL', isCore: true, departmentId: 'dept_math', departmentName: 'Mathematics', isActive: true },
  { id: 'sub_phy_o', code: 'PHY', name: 'Physics', level: 'O_LEVEL', isCore: true, departmentId: 'dept_sci', departmentName: 'Science', isActive: true },
  { id: 'sub_chem_o', code: 'CHEM', name: 'Chemistry', level: 'O_LEVEL', isCore: true, departmentId: 'dept_sci', departmentName: 'Science', isActive: true },
  { id: 'sub_bio_o', code: 'BIO', name: 'Biology', level: 'O_LEVEL', isCore: true, departmentId: 'dept_sci', departmentName: 'Science', isActive: true },
  { id: 'sub_eng_o', code: 'ENG', name: 'English Language', level: 'O_LEVEL', isCore: true, departmentId: 'dept_lang', departmentName: 'Languages', isActive: true },
  { id: 'sub_kisw_o', code: 'KISW', name: 'Kiswahili', level: 'O_LEVEL', isCore: true, departmentId: 'dept_lang', departmentName: 'Languages', isActive: true },
  { id: 'sub_geo_o', code: 'GEO', name: 'Geography', level: 'O_LEVEL', isCore: true, departmentId: 'dept_hum', departmentName: 'Humanities', isActive: true },
  { id: 'sub_hist_o', code: 'HIST', name: 'History', level: 'O_LEVEL', isCore: true, departmentId: 'dept_hum', departmentName: 'Humanities', isActive: true },
  { id: 'sub_civ_o', code: 'CIV', name: 'Civics', level: 'O_LEVEL', isCore: true, departmentId: 'dept_hum', departmentName: 'Humanities', isActive: true },
  // A-Level
  { id: 'sub_adv_math', code: 'ADVM', name: 'Advanced Mathematics', level: 'A_LEVEL', isCore: false, departmentId: 'dept_math', departmentName: 'Mathematics', isActive: true },
  { id: 'sub_adv_phy', code: 'APHY', name: 'Physics (A-Level)', level: 'A_LEVEL', isCore: false, departmentId: 'dept_sci', departmentName: 'Science', isActive: true },
  { id: 'sub_adv_chem', code: 'ACHEM', name: 'Chemistry (A-Level)', level: 'A_LEVEL', isCore: false, departmentId: 'dept_sci', departmentName: 'Science', isActive: true },
  { id: 'sub_adv_bio', code: 'ABIO', name: 'Biology (A-Level)', level: 'A_LEVEL', isCore: false, departmentId: 'dept_sci', departmentName: 'Science', isActive: true },
  { id: 'sub_adv_geo', code: 'AGEO', name: 'Geography (A-Level)', level: 'A_LEVEL', isCore: false, departmentId: 'dept_hum', departmentName: 'Humanities', isActive: true },
  { id: 'sub_adv_econ', code: 'ECON', name: 'Economics', level: 'A_LEVEL', isCore: false, departmentId: 'dept_comm', departmentName: 'Commercial', isActive: true },
  { id: 'sub_adv_hist', code: 'AHIST', name: 'History (A-Level)', level: 'A_LEVEL', isCore: false, departmentId: 'dept_hum', departmentName: 'Humanities', isActive: true },
  { id: 'sub_gs', code: 'GS', name: 'General Studies (Compulsory)', level: 'A_LEVEL', isCore: true, departmentId: 'dept_hum', departmentName: 'Humanities', isActive: true },
  { id: 'sub_bam', code: 'BAM', name: 'Basic Applied Mathematics (BAM)', level: 'A_LEVEL', isCore: false, departmentId: 'dept_math', departmentName: 'Mathematics', isActive: true },
];

export const INITIAL_COMBINATIONS: SubjectCombination[] = [
  { id: 'comb_pcm', code: 'PCM', name: 'Physics, Chemistry, Advanced Mathematics', subjectIds: ['sub_adv_phy', 'sub_adv_chem', 'sub_adv_math'], compulsorySubIds: ['sub_gs'], description: 'Premier Science & Engineering Combination', isActive: true },
  { id: 'comb_pcb', code: 'PCB', name: 'Physics, Chemistry, Biology', subjectIds: ['sub_adv_phy', 'sub_adv_chem', 'sub_adv_bio'], compulsorySubIds: ['sub_gs', 'sub_bam'], description: 'Medical, Pharmacy & Biological Sciences', isActive: true },
  { id: 'comb_hgl', code: 'HGL', name: 'History, Geography, English Language', subjectIds: ['sub_adv_hist', 'sub_adv_geo', 'sub_eng_o'], compulsorySubIds: ['sub_gs', 'sub_bam'], description: 'Law, International Relations, & Social Sciences', isActive: true },
  { id: 'comb_egm', code: 'EGM', name: 'Economics, Geography, Advanced Mathematics', subjectIds: ['sub_adv_econ', 'sub_adv_geo', 'sub_adv_math'], compulsorySubIds: ['sub_gs'], description: 'Finance, Actuarial & Data Sciences', isActive: true },
  { id: 'comb_cbg', code: 'CBG', name: 'Chemistry, Biology, Geography', subjectIds: ['sub_adv_chem', 'sub_adv_bio', 'sub_adv_geo'], compulsorySubIds: ['sub_gs', 'sub_bam'], description: 'Environmental Sciences & Agriculture', isActive: true },
];

export const INITIAL_CLASSES: ClassStream[] = [
  { id: 'cls_f1_a', name: 'Form I A', level: 'FORM_I', educationLevel: 'O_LEVEL', streamName: 'A', academicYear: '2026', classTeacherId: 'tch_06', classTeacherName: 'Mwl. Emmanuel P. Shirima', capacity: 45, roomNumber: 'Block A - 01' },
  { id: 'cls_f1_b', name: 'Form I B', level: 'FORM_I', educationLevel: 'O_LEVEL', streamName: 'B', academicYear: '2026', capacity: 45, roomNumber: 'Block A - 02' },
  { id: 'cls_f2_a', name: 'Form II A', level: 'FORM_II', educationLevel: 'O_LEVEL', streamName: 'A', academicYear: '2026', capacity: 45, roomNumber: 'Block A - 03' },
  { id: 'cls_f3_a', name: 'Form III A', level: 'FORM_III', educationLevel: 'O_LEVEL', streamName: 'A', academicYear: '2026', capacity: 45, roomNumber: 'Block B - 01' },
  { id: 'cls_f4_a', name: 'Form IV A', level: 'FORM_IV', educationLevel: 'O_LEVEL', streamName: 'A', academicYear: '2026', classTeacherId: 'tch_05', classTeacherName: 'Mwl. Asha M. Salum', capacity: 45, roomNumber: 'Block B - 03' },
  { id: 'cls_f4_b', name: 'Form IV B', level: 'FORM_IV', educationLevel: 'O_LEVEL', streamName: 'B', academicYear: '2026', capacity: 45, roomNumber: 'Block B - 04' },
  { id: 'cls_f5_pcm', name: 'Form V Science (PCM)', level: 'FORM_V', educationLevel: 'A_LEVEL', streamName: 'PCM', academicYear: '2026', classTeacherId: 'tch_01', classTeacherName: 'Mwl. Grace K. Mwita', capacity: 35, roomNumber: 'Science Complex 01' },
  { id: 'cls_f5_pcb', name: 'Form V Science (PCB)', level: 'FORM_V', educationLevel: 'A_LEVEL', streamName: 'PCB', academicYear: '2026', capacity: 35, roomNumber: 'Science Complex 02' },
  { id: 'cls_f6_pcm', name: 'Form VI Science (PCM)', level: 'FORM_VI', educationLevel: 'A_LEVEL', streamName: 'PCM', academicYear: '2026', capacity: 35, roomNumber: 'Senior Hall 01' },
];

export const INITIAL_TEACHERS: Teacher[] = [
  { id: 'tch_01', staffId: 'TSC-9941', fullName: 'Mwl. Grace K. Mwita', email: 'academic@kilimanjarostar.sc.tz', phone: '0754890111', gender: 'F', qualification: 'M.Ed Curriculum & Assessment, B.Sc Ed (UDSM)', departmentId: 'dept_sci', departmentName: 'Science', positions: ['Academic Master', 'Physics Teacher'], roles: ['ACADEMIC_MASTER', 'SUBJECT_TEACHER'], isActive: true, joinDate: '2019-01-10' },
  { id: 'tch_02', staffId: 'TSC-8812', fullName: 'Mwl. Baraka E. Mushi', email: 'headmaster@kilimanjarostar.sc.tz', phone: '0754112233', gender: 'M', qualification: 'M.A Educational Leadership (OUT), B.A Ed', departmentId: 'dept_hum', departmentName: 'Humanities', positions: ['Headmaster'], roles: ['HEAD_TEACHER'], isActive: true, joinDate: '2016-03-01' },
  { id: 'tch_03', staffId: 'TSC-7754', fullName: 'Mwl. Rehema S. Mrema', email: 'deputy@kilimanjarostar.sc.tz', phone: '0767223344', gender: 'F', qualification: 'B.Sc with Education (UDSM)', departmentId: 'dept_sci', departmentName: 'Science', positions: ['Deputy Head Teacher', 'Chemistry Teacher'], roles: ['DEPUTY_HEAD', 'SUBJECT_TEACHER'], isActive: true, joinDate: '2018-06-15' },
  { id: 'tch_04', staffId: 'TSC-6632', fullName: 'Mwl. Daudi J. Tarimo', email: 'hod.science@kilimanjarostar.sc.tz', phone: '0784334455', gender: 'M', qualification: 'B.Sc Ed (Biology & Chemistry)', departmentId: 'dept_sci', departmentName: 'Science', positions: ['Head of Department Science', 'Biology Teacher'], roles: ['HEAD_OF_DEPARTMENT', 'SUBJECT_TEACHER'], isActive: true, joinDate: '2020-02-01' },
  { id: 'tch_05', staffId: 'TSC-5521', fullName: 'Mwl. Asha M. Salum', email: 'classteacher@kilimanjarostar.sc.tz', phone: '0715445566', gender: 'F', qualification: 'B.Sc Mathematics & Statistics Ed (UDOM)', departmentId: 'dept_math', departmentName: 'Mathematics', positions: ['Class Teacher Form IV A', 'Mathematics Teacher'], roles: ['CLASS_TEACHER', 'SUBJECT_TEACHER'], isActive: true, joinDate: '2021-08-10' },
  { id: 'tch_06', staffId: 'TSC-4410', fullName: 'Mwl. Emmanuel P. Shirima', email: 'subject@kilimanjarostar.sc.tz', phone: '0752556677', gender: 'M', qualification: 'B.A Ed History & Kiswahili (SUZA)', departmentId: 'dept_hum', departmentName: 'Humanities', positions: ['Subject Teacher History'], roles: ['SUBJECT_TEACHER'], isActive: true, joinDate: '2022-01-12' },
  { id: 'tch_07', staffId: 'TSC-3309', fullName: 'Mwl. Tumaini L. Swai', email: 'hod.languages@kilimanjarostar.sc.tz', phone: '0765667788', gender: 'F', qualification: 'M.A Linguistics, B.A Ed', departmentId: 'dept_lang', departmentName: 'Languages', positions: ['Head of Department Languages'], roles: ['HEAD_OF_DEPARTMENT', 'SUBJECT_TEACHER'], isActive: true, joinDate: '2017-09-01' },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std_01',
    schoolId: 'school_klm_01',
    admissionNumber: 'ELM/2026/0101',
    fullName: 'Kelvin David Mushi',
    gender: 'M',
    dateOfBirth: '2008-04-12',
    admissionDate: '2023-01-15',
    classId: 'cls_f4_a',
    className: 'Form IV A',
    level: 'FORM_IV',
    educationLevel: 'O_LEVEL',
    status: 'ACTIVE',
    guardianName: 'David Mushi',
    guardianPhone: '0754998877',
    guardianEmail: 'parent@kilimanjarostar.sc.tz',
    guardianRelationship: 'Father',
    address: 'Plot 45, Nansio, Ukerewe',
    emergencyContact: '0754998877',
    notes: 'Class Prefect. Consistently high achiever in sciences.',
  },
  {
    id: 'std_02',
    schoolId: 'school_klm_01',
    admissionNumber: 'ELM/2026/0102',
    fullName: 'Neema Joseph Lyimo',
    gender: 'F',
    dateOfBirth: '2008-08-25',
    admissionDate: '2023-01-15',
    classId: 'cls_f4_a',
    className: 'Form IV A',
    level: 'FORM_IV',
    educationLevel: 'O_LEVEL',
    status: 'ACTIVE',
    guardianName: 'David Mushi', // Linked to same parent account for multi-child testing
    guardianPhone: '0754998877',
    guardianEmail: 'parent@kilimanjarostar.sc.tz',
    guardianRelationship: 'Guardian / Uncle',
    address: 'Plot 45, Nansio, Ukerewe',
    emergencyContact: '0754998877',
    notes: 'Member of Mathematics club.',
  },
  {
    id: 'std_03',
    schoolId: 'school_klm_01',
    admissionNumber: 'ELM/2026/0103',
    fullName: 'Baraka Simon Temba',
    gender: 'M',
    dateOfBirth: '2008-02-18',
    admissionDate: '2023-01-15',
    classId: 'cls_f4_a',
    className: 'Form IV A',
    level: 'FORM_IV',
    educationLevel: 'O_LEVEL',
    status: 'ACTIVE',
    guardianName: 'Simon Temba',
    guardianPhone: '0768112233',
    guardianRelationship: 'Father',
    address: 'Mwanza Road, Nansio',
    emergencyContact: '0768112233',
  },
  {
    id: 'std_04',
    schoolId: 'school_klm_01',
    admissionNumber: 'ELM/2026/0104',
    fullName: 'Fatma Hassan Ally',
    gender: 'F',
    dateOfBirth: '2008-11-03',
    admissionDate: '2023-01-15',
    classId: 'cls_f4_a',
    className: 'Form IV A',
    level: 'FORM_IV',
    educationLevel: 'O_LEVEL',
    status: 'ACTIVE',
    guardianName: 'Hassan Ally',
    guardianPhone: '0714223344',
    guardianRelationship: 'Father',
    address: 'Ukara ferry lane',
    emergencyContact: '0714223344',
  },
  {
    id: 'std_05',
    schoolId: 'school_klm_01',
    admissionNumber: 'ELM/2026/0201',
    fullName: 'Joshua Lucas Mwita',
    gender: 'M',
    dateOfBirth: '2006-05-14',
    admissionDate: '2025-07-10',
    classId: 'cls_f5_pcm',
    className: 'Form V Science (PCM)',
    level: 'FORM_V',
    educationLevel: 'A_LEVEL',
    combinationId: 'comb_pcm',
    combinationCode: 'PCM',
    status: 'ACTIVE',
    guardianName: 'Lucas Mwita',
    guardianPhone: '0784556677',
    guardianRelationship: 'Father',
    address: 'Bwiru, Mwanza',
    emergencyContact: '0784556677',
    notes: 'Admitted from Nsumba Secondary School (Division I - 9 points).',
  },
  {
    id: 'std_06',
    schoolId: 'school_klm_01',
    admissionNumber: 'ELM/2026/0202',
    fullName: 'Anitha Charles Kimaro',
    gender: 'F',
    dateOfBirth: '2006-09-22',
    admissionDate: '2025-07-10',
    classId: 'cls_f5_pcm',
    className: 'Form V Science (PCM)',
    level: 'FORM_V',
    educationLevel: 'A_LEVEL',
    combinationId: 'comb_pcm',
    combinationCode: 'PCM',
    status: 'ACTIVE',
    guardianName: 'Charles Kimaro',
    guardianPhone: '0754778899',
    guardianRelationship: 'Father',
    address: 'Kagunguli, Ukerewe',
    emergencyContact: '0754778899',
  },
  {
    id: 'std_07',
    schoolId: 'school_klm_01',
    admissionNumber: 'ELM/2026/0011',
    fullName: 'Rashid Omari Bakari',
    gender: 'M',
    dateOfBirth: '2011-01-19',
    admissionDate: '2026-01-08',
    classId: 'cls_f1_a',
    className: 'Form I A',
    level: 'FORM_I',
    educationLevel: 'O_LEVEL',
    status: 'ACTIVE',
    guardianName: 'Omari Bakari',
    guardianPhone: '0767889900',
    guardianRelationship: 'Father',
    address: 'Murutunguru, Ukerewe',
    emergencyContact: '0767889900',
  },
];

export const INITIAL_EXAMS: Examination[] = [
  {
    id: 'exam_01',
    name: 'Mid-Term Assessment Term 1 2026',
    type: 'MID_TERM',
    academicYear: '2026',
    term: 'Term 1',
    level: 'FORM_IV',
    startDate: '2026-03-10',
    endDate: '2026-03-20',
    maxMarks: 100,
    passMark: 30,
    isPublished: true,
    status: 'PUBLISHED',
    gradingSchemeId: 'scheme_o_level_standard',
  },
  {
    id: 'exam_02',
    name: 'Form V Pre-National Assessment 2026',
    type: 'SERIES',
    academicYear: '2026',
    term: 'Term 1',
    level: 'FORM_V',
    startDate: '2026-03-15',
    endDate: '2026-03-25',
    maxMarks: 100,
    passMark: 40,
    isPublished: false,
    status: 'UNDER_REVIEW',
    gradingSchemeId: 'scheme_a_level_standard',
  },
  {
    id: 'exam_03',
    name: 'Form I Diagnostic Test 2026',
    type: 'MONTHLY',
    academicYear: '2026',
    term: 'Term 1',
    level: 'FORM_I',
    startDate: '2026-04-05',
    endDate: '2026-04-12',
    maxMarks: 100,
    passMark: 30,
    isPublished: false,
    status: 'DRAFT',
    gradingSchemeId: 'scheme_o_level_standard',
  },
];

export const INITIAL_MARKS: MarkEntry[] = [
  // Kelvin David Mushi (std_01) in Mid-Term Form IV (exam_01)
  { id: 'mk_01', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_math_o', studentId: 'std_01', studentName: 'Kelvin David Mushi', admissionNumber: 'ELM/2026/0101', rawScore: 88, isAbsent: false, grade: 'A', points: 1, status: 'PUBLISHED', teacherId: 'tch_05', teacherName: 'Mwl. Asha M. Salum', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_02', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_phy_o', studentId: 'std_01', studentName: 'Kelvin David Mushi', admissionNumber: 'ELM/2026/0101', rawScore: 82, isAbsent: false, grade: 'A', points: 1, status: 'PUBLISHED', teacherId: 'tch_01', teacherName: 'Mwl. Grace K. Mwita', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_03', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_chem_o', studentId: 'std_01', studentName: 'Kelvin David Mushi', admissionNumber: 'ELM/2026/0101', rawScore: 78, isAbsent: false, grade: 'A', points: 1, status: 'PUBLISHED', teacherId: 'tch_03', teacherName: 'Mwl. Rehema S. Mrema', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_04', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_bio_o', studentId: 'std_01', studentName: 'Kelvin David Mushi', admissionNumber: 'ELM/2026/0101', rawScore: 74, isAbsent: false, grade: 'B', points: 2, status: 'PUBLISHED', teacherId: 'tch_04', teacherName: 'Mwl. Daudi J. Tarimo', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_05', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_eng_o', studentId: 'std_01', studentName: 'Kelvin David Mushi', admissionNumber: 'ELM/2026/0101', rawScore: 71, isAbsent: false, grade: 'B', points: 2, status: 'PUBLISHED', teacherId: 'tch_07', teacherName: 'Mwl. Tumaini L. Swai', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_06', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_kisw_o', studentId: 'std_01', studentName: 'Kelvin David Mushi', admissionNumber: 'ELM/2026/0101', rawScore: 84, isAbsent: false, grade: 'A', points: 1, status: 'PUBLISHED', teacherId: 'tch_06', teacherName: 'Mwl. Emmanuel P. Shirima', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_07', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_geo_o', studentId: 'std_01', studentName: 'Kelvin David Mushi', admissionNumber: 'ELM/2026/0101', rawScore: 76, isAbsent: false, grade: 'A', points: 1, status: 'PUBLISHED', teacherId: 'tch_06', teacherName: 'Mwl. Emmanuel P. Shirima', updatedAt: '2026-03-21T10:00:00Z' },

  // Neema Joseph Lyimo (std_02)
  { id: 'mk_08', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_math_o', studentId: 'std_02', studentName: 'Neema Joseph Lyimo', admissionNumber: 'ELM/2026/0102', rawScore: 79, isAbsent: false, grade: 'A', points: 1, status: 'PUBLISHED', teacherId: 'tch_05', teacherName: 'Mwl. Asha M. Salum', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_09', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_phy_o', studentId: 'std_02', studentName: 'Neema Joseph Lyimo', admissionNumber: 'ELM/2026/0102', rawScore: 68, isAbsent: false, grade: 'B', points: 2, status: 'PUBLISHED', teacherId: 'tch_01', teacherName: 'Mwl. Grace K. Mwita', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_10', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_chem_o', studentId: 'std_02', studentName: 'Neema Joseph Lyimo', admissionNumber: 'ELM/2026/0102', rawScore: 72, isAbsent: false, grade: 'B', points: 2, status: 'PUBLISHED', teacherId: 'tch_03', teacherName: 'Mwl. Rehema S. Mrema', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_11', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_bio_o', studentId: 'std_02', studentName: 'Neema Joseph Lyimo', admissionNumber: 'ELM/2026/0102', rawScore: 81, isAbsent: false, grade: 'A', points: 1, status: 'PUBLISHED', teacherId: 'tch_04', teacherName: 'Mwl. Daudi J. Tarimo', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_12', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_eng_o', studentId: 'std_02', studentName: 'Neema Joseph Lyimo', admissionNumber: 'ELM/2026/0102', rawScore: 86, isAbsent: false, grade: 'A', points: 1, status: 'PUBLISHED', teacherId: 'tch_07', teacherName: 'Mwl. Tumaini L. Swai', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_13', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_kisw_o', studentId: 'std_02', studentName: 'Neema Joseph Lyimo', admissionNumber: 'ELM/2026/0102', rawScore: 90, isAbsent: false, grade: 'A', points: 1, status: 'PUBLISHED', teacherId: 'tch_06', teacherName: 'Mwl. Emmanuel P. Shirima', updatedAt: '2026-03-21T10:00:00Z' },
  { id: 'mk_14', examinationId: 'exam_01', classId: 'cls_f4_a', subjectId: 'sub_geo_o', studentId: 'std_02', studentName: 'Neema Joseph Lyimo', admissionNumber: 'ELM/2026/0102', rawScore: 75, isAbsent: false, grade: 'A', points: 1, status: 'PUBLISHED', teacherId: 'tch_06', teacherName: 'Mwl. Emmanuel P. Shirima', updatedAt: '2026-03-21T10:00:00Z' },

  // A-Level Joshua (std_05) in Exam 2 (UNDER_REVIEW / SUBMITTED - NOT YET PUBLISHED)
  { id: 'mk_15', examinationId: 'exam_02', classId: 'cls_f5_pcm', subjectId: 'sub_adv_phy', studentId: 'std_05', studentName: 'Joshua Lucas Mwita', admissionNumber: 'ELM/2026/0201', rawScore: 75, isAbsent: false, grade: 'B', points: 2, status: 'SUBMITTED', teacherId: 'tch_01', teacherName: 'Mwl. Grace K. Mwita', updatedAt: '2026-03-22T10:00:00Z' },
  { id: 'mk_16', examinationId: 'exam_02', classId: 'cls_f5_pcm', subjectId: 'sub_adv_chem', studentId: 'std_05', studentName: 'Joshua Lucas Mwita', admissionNumber: 'ELM/2026/0201', rawScore: 71, isAbsent: false, grade: 'B', points: 2, status: 'SUBMITTED', teacherId: 'tch_03', teacherName: 'Mwl. Rehema S. Mrema', updatedAt: '2026-03-22T10:00:00Z' },
  { id: 'mk_17', examinationId: 'exam_02', classId: 'cls_f5_pcm', subjectId: 'sub_adv_math', studentId: 'std_05', studentName: 'Joshua Lucas Mwita', admissionNumber: 'ELM/2026/0201', rawScore: 84, isAbsent: false, grade: 'A', points: 1, status: 'SUBMITTED', teacherId: 'tch_05', teacherName: 'Mwl. Asha M. Salum', updatedAt: '2026-03-22T10:00:00Z' },
];

export const INITIAL_SUBMISSIONS: ExamSubmissionSummary[] = [
  {
    id: 'subm_01',
    examinationId: 'exam_01',
    examName: 'Mid-Term Assessment Term 1 2026',
    classId: 'cls_f4_a',
    className: 'Form IV A',
    subjectId: 'sub_math_o',
    subjectName: 'Basic Mathematics',
    subjectCode: 'MATH',
    teacherId: 'tch_05',
    teacherName: 'Mwl. Asha M. Salum',
    totalStudents: 4,
    submittedCount: 4,
    absentCount: 0,
    averageScore: 78.5,
    highestScore: 88,
    lowestScore: 65,
    status: 'PUBLISHED',
    submittedAt: '2026-03-20T14:30:00Z',
    reviewedBy: 'Mwl. Grace K. Mwita',
    reviewedAt: '2026-03-21T09:15:00Z',
    publishedAt: '2026-03-22T10:00:00Z',
    publishedBy: 'Mwl. Grace K. Mwita',
  },
  {
    id: 'subm_02',
    examinationId: 'exam_02',
    examName: 'Form V Pre-National Assessment 2026',
    classId: 'cls_f5_pcm',
    className: 'Form V Science (PCM)',
    subjectId: 'sub_adv_phy',
    subjectName: 'Physics (A-Level)',
    subjectCode: 'APHY',
    teacherId: 'tch_01',
    teacherName: 'Mwl. Grace K. Mwita',
    totalStudents: 2,
    submittedCount: 2,
    absentCount: 0,
    averageScore: 72.0,
    highestScore: 75,
    lowestScore: 69,
    status: 'UNDER_REVIEW',
    submittedAt: '2026-03-25T11:00:00Z',
  },
];

export const INITIAL_ATTENDANCE: StudentAttendanceRecord[] = [
  { id: 'att_01', classId: 'cls_f4_a', date: '2026-03-24', studentId: 'std_01', studentName: 'Kelvin David Mushi', admissionNumber: 'ELM/2026/0101', status: 'PRESENT', markedBy: 'tch_05', markedByName: 'Mwl. Asha M. Salum', updatedAt: '2026-03-24T08:05:00Z' },
  { id: 'att_02', classId: 'cls_f4_a', date: '2026-03-24', studentId: 'std_02', studentName: 'Neema Joseph Lyimo', admissionNumber: 'ELM/2026/0102', status: 'PRESENT', markedBy: 'tch_05', markedByName: 'Mwl. Asha M. Salum', updatedAt: '2026-03-24T08:05:00Z' },
  { id: 'att_03', classId: 'cls_f4_a', date: '2026-03-24', studentId: 'std_03', studentName: 'Baraka Simon Temba', admissionNumber: 'ELM/2026/0103', status: 'ABSENT', remark: 'No official note provided by parent', markedBy: 'tch_05', markedByName: 'Mwl. Asha M. Salum', updatedAt: '2026-03-24T08:05:00Z' },
  { id: 'att_04', classId: 'cls_f4_a', date: '2026-03-24', studentId: 'std_04', studentName: 'Fatma Hassan Ally', admissionNumber: 'ELM/2026/0104', status: 'PRESENT', markedBy: 'tch_05', markedByName: 'Mwl. Asha M. Salum', updatedAt: '2026-03-24T08:05:00Z' },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann_01',
    title: 'Release of Mid-Term Form IV Results & Parent Consultations',
    titleSwahili: 'Kutangazwa kwa Matokeo ya Nusu Muhula Kidato cha IV na Kikao cha Wazazi',
    content: 'All parents and guardians of Form IV candidates are advised that Mid-Term examination results have been published on ELIMU PRO. Hardcopy consultation day is scheduled for this Friday.',
    contentSwahili: 'Wazazi na walezi wote wa wanafunzi wa Kidato cha Nne wanataarifiwa kuwa matokeo ya mtihani wa nusu muhula yametangazwa kwenye mfumo wa ELIMU PRO. Siku ya mashauriano shuleni itakuwa Ijumaa hii.',
    targetRoles: ['PARENT', 'TEACHER', 'STUDENT'] as any,
    priority: 'HIGH',
    authorName: 'Mwl. Baraka E. Mushi (Headmaster)',
    date: '2026-03-22',
  },
  {
    id: 'ann_02',
    title: 'National Form VI Practical Science Preparations',
    titleSwahili: 'Maandalizi ya Mitihani ya Vitendo ya Sayansi Kidato cha Sita',
    content: 'Science laboratories will remain open on Saturday mornings for Form VI PCM and PCB candidates under supervision of the Head of Department.',
    contentSwahili: 'Maabara za sayansi zitakuwa wazi Jumamosi asubuhi kwa ajili ya wanafunzi wa Kidato cha VI michepuo ya PCM na PCB chini ya usimamizi wa Mkuu wa Idara.',
    targetRoles: ['HEAD_OF_DEPARTMENT', 'SUBJECT_TEACHER', 'STUDENT'] as any,
    priority: 'NORMAL',
    authorName: 'Mwl. Daudi J. Tarimo (HoD Science)',
    date: '2026-03-20',
  },
];

export const INITIAL_GROUPS: MessageGroup[] = [
  { id: 'grp_01', name: 'Form IV A Parents & Teachers Forum', description: 'Official academic consultation & class updates group', classId: 'cls_f4_a', type: 'CLASS', createdBy: 'tch_05', createdByName: 'Mwl. Asha M. Salum', createdAt: '2026-01-20', memberCount: 32 },
  { id: 'grp_02', name: 'Science Department Academic Group', description: 'Internal syllabus coverage and practical exam coordination', departmentId: 'dept_sci', type: 'DEPARTMENT', createdBy: 'tch_04', createdByName: 'Mwl. Daudi J. Tarimo', createdAt: '2026-01-15', memberCount: 8 },
];

export const INITIAL_MESSAGES: GroupMessage[] = [
  { id: 'msg_01', groupId: 'grp_01', senderId: 'tch_05', senderName: 'Mwl. Asha M. Salum', senderRole: 'CLASS_TEACHER', content: 'Habari za asubuhi wazazi. Tunawashukuru kwa ushirikiano. Matokeo ya Mid-Term yametangazwa rasmi na mnaweza kuyaona kupitia akaunti zenu.', timestamp: '2026-03-22T08:30:00Z', isPinned: true },
  { id: 'msg_02', groupId: 'grp_01', senderId: 'usr_parent', senderName: 'David Mushi (Mzazi wa Kelvin)', senderRole: 'PARENT', content: 'Asante sana Mwalimu Asha. Nimeyaona matokeo ya Kelvin na nina furaha na maendeleo yake kwenye masomo ya Sayansi.', timestamp: '2026-03-22T09:12:00Z' },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  { id: 'aud_01', userId: 'tch_01', userName: 'Mwl. Grace K. Mwita', userRole: 'ACADEMIC_MASTER', action: 'RESULT_PUBLICATION', category: 'ACADEMIC', details: 'Form IV A Mid-Term results approved and published to portal and SMS gateway.', timestamp: '2026-03-22T10:00:00Z', ipAddress: '197.250.21.4' },
  { id: 'aud_02', userId: 'tch_05', userName: 'Mwl. Asha M. Salum', userRole: 'CLASS_TEACHER', action: 'ATTENDANCE_SUBMIT', category: 'ATTENDANCE', details: 'Form IV A daily attendance registered (3 Present, 1 Absent).', timestamp: '2026-03-24T08:05:00Z', ipAddress: '197.250.21.4' },
  { id: 'aud_03', userId: 'usr_admin', userName: 'System Admin', userRole: 'SCHOOL_ADMIN', action: 'SECURITY_LOGIN', category: 'SECURITY', details: 'Successful administrator login with session encryption.', timestamp: '2026-03-24T07:30:00Z', ipAddress: '197.250.21.1' },
];

export const INITIAL_USERS: User[] = [
  { id: 'usr_super', name: 'Super Administrator', email: 'superadmin@elimupro.tz', role: 'SUPER_ADMIN', schoolId: 'school_tura_01', isActive: true, twoFactorEnabled: true },
  { id: 'usr_admin', name: 'Mwl. Josephat K. Lyimo (Registrar)', email: 'registrar@turasecondary.sc.tz', role: 'SCHOOL_ADMIN', schoolId: 'school_tura_01', isActive: true },
  { id: 'usr_head', name: 'Mwl. Baraka E. Mushi', email: 'headmaster@turasecondary.sc.tz', role: 'HEAD_TEACHER', schoolId: 'school_tura_01', staffId: 'tch_02', isActive: true },
  { id: 'usr_deputy', name: 'Mwl. Rehema S. Mrema', email: 'deputy@turasecondary.sc.tz', role: 'DEPUTY_HEAD', schoolId: 'school_tura_01', staffId: 'tch_03', isActive: true },
  { id: 'usr_academic', name: 'Mwl. Grace K. Mwita', email: 'academic@turasecondary.sc.tz', role: 'ACADEMIC_MASTER', schoolId: 'school_tura_01', staffId: 'tch_01', isActive: true },
  { id: 'usr_hod', name: 'Mwl. Daudi J. Tarimo', email: 'hod.science@turasecondary.sc.tz', role: 'HEAD_OF_DEPARTMENT', schoolId: 'school_tura_01', staffId: 'tch_04', departmentId: 'dept_sci', isActive: true },
  { id: 'usr_classteacher', name: 'Mwl. Asha M. Salum', email: 'classteacher@turasecondary.sc.tz', role: 'CLASS_TEACHER', schoolId: 'school_tura_01', staffId: 'tch_05', assignedClassId: 'cls_f4_a', isActive: true },
  { id: 'usr_subject', name: 'Mwl. Emmanuel P. Shirima', email: 'subject@turasecondary.sc.tz', role: 'SUBJECT_TEACHER', schoolId: 'school_tura_01', staffId: 'tch_06', isActive: true },
  { id: 'usr_parent', name: 'David Mushi (Guardian)', email: 'parent@turasecondary.sc.tz', phone: '0754998877', role: 'PARENT', schoolId: 'school_tura_01', linkedStudentIds: ['std_01', 'std_02'], isActive: true },
  { id: 'usr_student', name: 'Kelvin David Mushi', email: 'student@turasecondary.sc.tz', role: 'STUDENT', schoolId: 'school_tura_01', studentId: 'std_01', isActive: true },
];
